import { Dosis } from "next/font/google";

import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"


import "./globals.css";

const inter = Dosis({
  weight: '400',
  size: '20',
  subsets: ["latin"]
});

export const metadata = {
  title: "Declic Studio MG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (

      <html lang="en">
        <body className={inter.className}>
          <>
            {children}
          </>
          <SpeedInsights />
          <Analytics />
        </body>
      </html>
  
  );
}
