
import React from "react";
import SideBar from "../component/admin/sidebar/sidebar";
import "../admin.css"

export const metadata = {
    title: "Admin | Art wear",
    description: "Generated by create next app",
};

const layout = ({ children }) => {
    return (

        <div>
            {children}
        </div>
    )
}

export default layout;